# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import base64
import typing

import httpx

from .client import Agora as BaseAgora
from .client import AsyncAgora as BaseAsyncAgora
from .core.domain import Area, Pool

_AUTH_MODE = typing.Literal["app-credentials", "basic"]


def _basic_auth_header(customer_id: str, customer_secret: str) -> str:
    encoded = base64.b64encode(f"{customer_id}:{customer_secret}".encode()).decode()
    return f"Basic {encoded}"


class Agora(BaseAgora):
    """
    Agora extends the base client with domain pool support for
    regional URL cycling and automatic domain selection.

    This client automatically:
    - Selects the best domain based on DNS resolution
    - Cycles through region prefixes on request failures
    - Supports US, EU, AP, and CN areas

    Parameters
    ----------
    area : Area
        The area to use for regional URL selection.

    app_id : str
        Your Agora App ID.

    app_certificate : str
        Your Agora App Certificate.

    customer_id : typing.Optional[str]
        Customer ID for Basic auth. When provided together with
        ``customer_secret``, the client uses
        ``Authorization: Basic base64(customer_id:customer_secret)``.
        When omitted the client operates in *app-credentials* mode and
        auto-generates a ConvoAI token per request.

    customer_secret : typing.Optional[str]
        Customer secret for Basic auth (required when ``customer_id`` is set).

    headers : typing.Optional[typing.Dict[str, str]]
        Additional headers to send with every request.

    timeout : typing.Optional[float]
        The timeout to be used, in seconds, for requests. By default the
        timeout is 60 seconds, unless a custom httpx client is used, in which
        case this default is not enforced.

    follow_redirects : typing.Optional[bool]
        Whether the default httpx client follows redirects or not, this is
        irrelevant if a custom httpx client is passed in.

    httpx_client : typing.Optional[httpx.Client]
        The httpx client to use for making requests, a preconfigured client is
        used by default, however this is useful should you want to pass in any
        custom httpx configuration.

    Examples
    --------
    # App-credentials mode (auto token generation per request)
    from agora_agent import Agora, Area

    client = Agora(
        area=Area.US,
        app_id="YOUR_APP_ID",
        app_certificate="YOUR_APP_CERTIFICATE",
    )

    # Basic auth mode
    from agora_agent import Agora, Area

    client = Agora(
        area=Area.US,
        app_id="YOUR_APP_ID",
        app_certificate="YOUR_APP_CERTIFICATE",
        customer_id="YOUR_CUSTOMER_ID",
        customer_secret="YOUR_CUSTOMER_SECRET",
    )
    """

    def __init__(
        self,
        *,
        area: Area,
        app_id: str,
        app_certificate: str,
        customer_id: typing.Optional[str] = None,
        customer_secret: typing.Optional[str] = None,
        headers: typing.Optional[typing.Dict[str, str]] = None,
        timeout: typing.Optional[float] = None,
        follow_redirects: typing.Optional[bool] = True,
        httpx_client: typing.Optional[httpx.Client] = None,
    ):
        self._pool = Pool(area)
        self.app_id = app_id
        self.app_certificate = app_certificate

        if customer_id is not None:
            if customer_secret is None:
                raise ValueError("customer_secret is required when customer_id is provided")
            self.auth_mode: _AUTH_MODE = "basic"
            authorization = _basic_auth_header(customer_id, customer_secret)
        else:
            self.auth_mode = "app-credentials"
            authorization = ""

        super().__init__(
            base_url=self._pool.get_current_url(),
            authorization=authorization,
            username="",
            password="",
            headers=headers,
            timeout=timeout,
            follow_redirects=follow_redirects,
            httpx_client=httpx_client,
        )

    @property
    def pool(self) -> Pool:
        """
        Get the underlying domain pool for advanced usage.
        You can use this to manually cycle regions or select the best domain.
        """
        return self._pool

    def next_region(self) -> None:
        """
        Cycle to the next region prefix in the pool.
        Call this when a request fails to try a different region.
        """
        self._pool.next_region()
        self._update_base_url()

    def select_best_domain(self) -> None:
        """
        Select the best domain using DNS resolution.
        This is automatically called periodically, but you can call it manually.
        """
        self._pool.select_best_domain()
        self._update_base_url()

    def get_current_url(self) -> str:
        """
        Get the current URL being used for requests.
        """
        return self._pool.get_current_url()

    def _update_base_url(self) -> None:
        """
        Update the base URL in the client wrapper to match the pool's current URL.
        """
        self._client_wrapper._base_url = self._pool.get_current_url()


class AsyncAgora(BaseAsyncAgora):
    """
    AsyncAgora extends the base async client with domain pool support for
    regional URL cycling and automatic domain selection.

    This client automatically:
    - Selects the best domain based on DNS resolution
    - Cycles through region prefixes on request failures
    - Supports US, EU, AP, and CN areas

    Parameters
    ----------
    area : Area
        The area to use for regional URL selection.

    app_id : str
        Your Agora App ID.

    app_certificate : str
        Your Agora App Certificate.

    customer_id : typing.Optional[str]
        Customer ID for Basic auth. When provided together with
        ``customer_secret``, the client uses
        ``Authorization: Basic base64(customer_id:customer_secret)``.
        When omitted the client operates in *app-credentials* mode and
        auto-generates a ConvoAI token per request.

    customer_secret : typing.Optional[str]
        Customer secret for Basic auth (required when ``customer_id`` is set).

    headers : typing.Optional[typing.Dict[str, str]]
        Additional headers to send with every request.

    timeout : typing.Optional[float]
        The timeout to be used, in seconds, for requests. By default the
        timeout is 60 seconds, unless a custom httpx client is used, in which
        case this default is not enforced.

    follow_redirects : typing.Optional[bool]
        Whether the default httpx client follows redirects or not, this is
        irrelevant if a custom httpx client is passed in.

    httpx_client : typing.Optional[httpx.AsyncClient]
        The httpx client to use for making requests, a preconfigured client is
        used by default, however this is useful should you want to pass in any
        custom httpx configuration.

    Examples
    --------
    # App-credentials mode (auto token generation per request)
    from agora_agent import AsyncAgora, Area

    client = AsyncAgora(
        area=Area.US,
        app_id="YOUR_APP_ID",
        app_certificate="YOUR_APP_CERTIFICATE",
    )

    # Basic auth mode
    from agora_agent import AsyncAgora, Area

    client = AsyncAgora(
        area=Area.US,
        app_id="YOUR_APP_ID",
        app_certificate="YOUR_APP_CERTIFICATE",
        customer_id="YOUR_CUSTOMER_ID",
        customer_secret="YOUR_CUSTOMER_SECRET",
    )
    """

    def __init__(
        self,
        *,
        area: Area,
        app_id: str,
        app_certificate: str,
        customer_id: typing.Optional[str] = None,
        customer_secret: typing.Optional[str] = None,
        headers: typing.Optional[typing.Dict[str, str]] = None,
        timeout: typing.Optional[float] = None,
        follow_redirects: typing.Optional[bool] = True,
        httpx_client: typing.Optional[httpx.AsyncClient] = None,
    ):
        self._pool = Pool(area)
        self.app_id = app_id
        self.app_certificate = app_certificate

        if customer_id is not None:
            if customer_secret is None:
                raise ValueError("customer_secret is required when customer_id is provided")
            self.auth_mode: _AUTH_MODE = "basic"
            authorization = _basic_auth_header(customer_id, customer_secret)
        else:
            self.auth_mode = "app-credentials"
            authorization = ""

        super().__init__(
            base_url=self._pool.get_current_url(),
            authorization=authorization,
            username="",
            password="",
            headers=headers,
            timeout=timeout,
            follow_redirects=follow_redirects,
            httpx_client=httpx_client,
        )

    @property
    def pool(self) -> Pool:
        """
        Get the underlying domain pool for advanced usage.
        You can use this to manually cycle regions or select the best domain.
        """
        return self._pool

    def next_region(self) -> None:
        """
        Cycle to the next region prefix in the pool.
        Call this when a request fails to try a different region.
        """
        self._pool.next_region()
        self._update_base_url()

    async def select_best_domain(self) -> None:
        """
        Select the best domain using DNS resolution (async).
        This is automatically called periodically, but you can call it manually.
        """
        await self._pool.select_best_domain_async()
        self._update_base_url()

    def get_current_url(self) -> str:
        """
        Get the current URL being used for requests.
        """
        return self._pool.get_current_url()

    def _update_base_url(self) -> None:
        """
        Update the base URL in the client wrapper to match the pool's current URL.
        """
        self._client_wrapper._base_url = self._pool.get_current_url()
