# This file was auto-generated by Fern from our API Definition.
# Modified to export regional clients as the public API.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from . import agents, phone_numbers, telephony
    from .regional_client import RegionalAgora as Agora
    from .regional_client import AsyncRegionalAgora as AsyncAgora
    from .area import GatewayArea, RegionalEndpointPool
    from .version import __version__

_dynamic_imports: typing.Dict[str, str] = {
    "Agora": ".regional_client",
    "AsyncAgora": ".regional_client",
    "GatewayArea": ".area",
    "RegionalEndpointPool": ".area",
    "__version__": ".version",
    "agents": ".agents",
    "phone_numbers": ".phone_numbers",
    "telephony": ".telephony",
}

_import_aliases: typing.Dict[str, str] = {
    "Agora": "RegionalAgora",
    "AsyncAgora": "AsyncRegionalAgora",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            actual_attr = _import_aliases.get(attr_name, attr_name)
            return getattr(module, actual_attr)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "Agora",
    "AsyncAgora",
    "GatewayArea",
    "RegionalEndpointPool",
    "__version__",
    "agents",
    "phone_numbers",
    "telephony",
]
