# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.unchecked_base_model import UncheckedBaseModel


class GetTurnsAgentsResponseTurnsItemMetricsSegmentedLatencyMsItem(UncheckedBaseModel):
    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    The name of the latency segment.
    
    When the LLM input modality is `text`, the returned segments are:
    - `algorithm_processing`: Algorithm processing delay.
    - `asr_ttlw`: ASR Time To Last Word (TTLW) in milliseconds.
    - `llm_ttft`: LLM Time To First Token (TTFT) in milliseconds.
    - `llm_ftfs`: LLM First Token To First Sentence (FTFS) in milliseconds.
    - `tts_ttfb`: TTS Time To First Byte (TTFB) in milliseconds.
    - `transport`: Network transmission delay in milliseconds. Not returned when the user is connected using the RTC Web SDK.
    
    When the LLM input modality is `audio`, the returned segments are:
    - `algorithm_processing`: Algorithm processing delay.
    - `asr_ttlw`: ASR Time To Last Word (TTLW) in milliseconds.
    - `llm_ttfa`: LLM Time To First Audio Byte (TTFA) in milliseconds.
    - `transport`: Network transmission delay in milliseconds. Not returned when the user is connected using the RTC Web SDK.
    """

    latency: typing.Optional[float] = pydantic.Field(default=None)
    """
    The latency in milliseconds for the segment.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
