# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.serialization import FieldMetadata
from ...core.unchecked_base_model import UncheckedBaseModel
from .get_turns_agents_response_turns_item_metrics_segmented_latency_ms_item import (
    GetTurnsAgentsResponseTurnsItemMetricsSegmentedLatencyMsItem,
)


class GetTurnsAgentsResponseTurnsItemMetrics(UncheckedBaseModel):
    """
    Latency metrics for the turn.
    """

    e_2_e_latency_ms: typing_extensions.Annotated[typing.Optional[int], FieldMetadata(alias="e2e_latency_ms")] = (
        pydantic.Field(default=None)
    )
    """
    The end-to-end latency in milliseconds for the turn.
    """

    segmented_latency_ms: typing.Optional[typing.List[GetTurnsAgentsResponseTurnsItemMetricsSegmentedLatencyMsItem]] = (
        pydantic.Field(default=None)
    )
    """
    A breakdown of latency by segment.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
