# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawPhoneNumberManagementClient, RawPhoneNumberManagementClient
from .types.add_phone_number_management_request_inbound_config import AddPhoneNumberManagementRequestInboundConfig
from .types.add_phone_number_management_request_outbound_config import AddPhoneNumberManagementRequestOutboundConfig
from .types.add_phone_number_management_request_provider import AddPhoneNumberManagementRequestProvider
from .types.add_phone_number_management_response import AddPhoneNumberManagementResponse
from .types.get_phone_number_management_response import GetPhoneNumberManagementResponse
from .types.list_phone_number_management_response_item import ListPhoneNumberManagementResponseItem
from .types.update_phone_number_management_request_inbound_config import UpdatePhoneNumberManagementRequestInboundConfig
from .types.update_phone_number_management_request_outbound_config import (
    UpdatePhoneNumberManagementRequestOutboundConfig,
)
from .types.update_phone_number_management_response import UpdatePhoneNumberManagementResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class PhoneNumberManagementClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawPhoneNumberManagementClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawPhoneNumberManagementClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawPhoneNumberManagementClient
        """
        return self._raw_client

    def list(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[ListPhoneNumberManagementResponseItem]:
        """
        Retrieve a list of all imported phone numbers under the current account.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[ListPhoneNumberManagementResponseItem]
            Request was successful. The response body contains a JSON array of phone number configurations.

        Examples
        --------
        from agoraio import Agora

        client = Agora(
            username="YOUR_USERNAME",
            password="YOUR_PASSWORD",
        )
        client.phone_number_management.list()
        """
        _response = self._raw_client.list(request_options=request_options)
        return _response.data

    def add(
        self,
        *,
        provider: AddPhoneNumberManagementRequestProvider,
        phone_number: str,
        label: str,
        inbound_config: AddPhoneNumberManagementRequestInboundConfig,
        outbound_config: AddPhoneNumberManagementRequestOutboundConfig,
        inbound: typing.Optional[bool] = OMIT,
        outbound: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AddPhoneNumberManagementResponse:
        """
        Import a pre-configured phone number that can be used for inbound or outbound calls.

        Parameters
        ----------
        provider : AddPhoneNumberManagementRequestProvider
            Number provider:
            - `byo`: BYO (Bring Your Own)
            - `twilio`: Twilio

        phone_number : str
            Telephone number in E.164 format.

        label : str
            A label used to identify the number.

        inbound_config : AddPhoneNumberManagementRequestInboundConfig
            SIP inbound call configuration.

        outbound_config : AddPhoneNumberManagementRequestOutboundConfig
            SIP outbound call configuration.

        inbound : typing.Optional[bool]
            Whether the number supports inbound calls.

        outbound : typing.Optional[bool]
            Whether the number supports outbound calls.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AddPhoneNumberManagementResponse
            Request was successful. The response body contains the result of the request.

        Examples
        --------
        from agoraio import Agora
        from agoraio.phone_number_management import (
            AddPhoneNumberManagementRequestInboundConfig,
            AddPhoneNumberManagementRequestOutboundConfig,
        )

        client = Agora(
            username="YOUR_USERNAME",
            password="YOUR_PASSWORD",
        )
        client.phone_number_management.add(
            provider="byo",
            phone_number="+19876543210",
            label="Sales Hotline",
            inbound=True,
            outbound=True,
            inbound_config=AddPhoneNumberManagementRequestInboundConfig(
                allowed_addresses=["112.126.15.64/27"],
            ),
            outbound_config=AddPhoneNumberManagementRequestOutboundConfig(
                address="xxx:xxx@sip.example.com",
                transport="tls",
            ),
        )
        """
        _response = self._raw_client.add(
            provider=provider,
            phone_number=phone_number,
            label=label,
            inbound_config=inbound_config,
            outbound_config=outbound_config,
            inbound=inbound,
            outbound=outbound,
            request_options=request_options,
        )
        return _response.data

    def get(
        self, phone_number: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetPhoneNumberManagementResponse:
        """
        Retrieve detailed information for a specific phone number.

        Parameters
        ----------
        phone_number : str
            Telephone number in E.164 format. For example, +11234567890.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetPhoneNumberManagementResponse
            Request was successful. The response body contains the result of the request.

        Examples
        --------
        from agoraio import Agora

        client = Agora(
            username="YOUR_USERNAME",
            password="YOUR_PASSWORD",
        )
        client.phone_number_management.get(
            phone_number="phone_number",
        )
        """
        _response = self._raw_client.get(phone_number, request_options=request_options)
        return _response.data

    def delete(self, phone_number: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Remove an imported phone number from the system.

        Note: This operation only removes the number configuration from the Agora system; the number stored with the phone service provider is not deleted. After calling this endpoint, the number stops receiving calls routed through this system. To delete the number from the service provider, remove it in the service provider's console.

        Parameters
        ----------
        phone_number : str
            Telephone number in E.164 format. For example, +11234567890.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from agoraio import Agora

        client = Agora(
            username="YOUR_USERNAME",
            password="YOUR_PASSWORD",
        )
        client.phone_number_management.delete(
            phone_number="phone_number",
        )
        """
        _response = self._raw_client.delete(phone_number, request_options=request_options)
        return _response.data

    def update(
        self,
        phone_number: str,
        *,
        inbound_config: typing.Optional[UpdatePhoneNumberManagementRequestInboundConfig] = OMIT,
        outbound_config: typing.Optional[UpdatePhoneNumberManagementRequestOutboundConfig] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UpdatePhoneNumberManagementResponse:
        """
        Update the configuration for a phone number.

        Parameters
        ----------
        phone_number : str
            Telephone number in E.164 format. For example, +11234567890.

        inbound_config : typing.Optional[UpdatePhoneNumberManagementRequestInboundConfig]
            Update inbound call configuration. Passing `null` will clear the configuration.

        outbound_config : typing.Optional[UpdatePhoneNumberManagementRequestOutboundConfig]
            Update outbound call configuration. Passing `null` will clear the configuration.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UpdatePhoneNumberManagementResponse
            Request was successful. The response body contains the result of the request.

        Examples
        --------
        from agoraio import Agora
        from agoraio.phone_number_management import (
            UpdatePhoneNumberManagementRequestInboundConfig,
            UpdatePhoneNumberManagementRequestOutboundConfig,
        )

        client = Agora(
            username="YOUR_USERNAME",
            password="YOUR_PASSWORD",
        )
        client.phone_number_management.update(
            phone_number="phone_number",
            inbound_config=UpdatePhoneNumberManagementRequestInboundConfig(
                pipeline_id="xxxxx",
            ),
            outbound_config=UpdatePhoneNumberManagementRequestOutboundConfig(
                pipeline_id="xxxxx",
            ),
        )
        """
        _response = self._raw_client.update(
            phone_number,
            inbound_config=inbound_config,
            outbound_config=outbound_config,
            request_options=request_options,
        )
        return _response.data


class AsyncPhoneNumberManagementClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawPhoneNumberManagementClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawPhoneNumberManagementClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawPhoneNumberManagementClient
        """
        return self._raw_client

    async def list(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[ListPhoneNumberManagementResponseItem]:
        """
        Retrieve a list of all imported phone numbers under the current account.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[ListPhoneNumberManagementResponseItem]
            Request was successful. The response body contains a JSON array of phone number configurations.

        Examples
        --------
        import asyncio

        from agoraio import AsyncAgora

        client = AsyncAgora(
            username="YOUR_USERNAME",
            password="YOUR_PASSWORD",
        )


        async def main() -> None:
            await client.phone_number_management.list()


        asyncio.run(main())
        """
        _response = await self._raw_client.list(request_options=request_options)
        return _response.data

    async def add(
        self,
        *,
        provider: AddPhoneNumberManagementRequestProvider,
        phone_number: str,
        label: str,
        inbound_config: AddPhoneNumberManagementRequestInboundConfig,
        outbound_config: AddPhoneNumberManagementRequestOutboundConfig,
        inbound: typing.Optional[bool] = OMIT,
        outbound: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AddPhoneNumberManagementResponse:
        """
        Import a pre-configured phone number that can be used for inbound or outbound calls.

        Parameters
        ----------
        provider : AddPhoneNumberManagementRequestProvider
            Number provider:
            - `byo`: BYO (Bring Your Own)
            - `twilio`: Twilio

        phone_number : str
            Telephone number in E.164 format.

        label : str
            A label used to identify the number.

        inbound_config : AddPhoneNumberManagementRequestInboundConfig
            SIP inbound call configuration.

        outbound_config : AddPhoneNumberManagementRequestOutboundConfig
            SIP outbound call configuration.

        inbound : typing.Optional[bool]
            Whether the number supports inbound calls.

        outbound : typing.Optional[bool]
            Whether the number supports outbound calls.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AddPhoneNumberManagementResponse
            Request was successful. The response body contains the result of the request.

        Examples
        --------
        import asyncio

        from agoraio import AsyncAgora
        from agoraio.phone_number_management import (
            AddPhoneNumberManagementRequestInboundConfig,
            AddPhoneNumberManagementRequestOutboundConfig,
        )

        client = AsyncAgora(
            username="YOUR_USERNAME",
            password="YOUR_PASSWORD",
        )


        async def main() -> None:
            await client.phone_number_management.add(
                provider="byo",
                phone_number="+19876543210",
                label="Sales Hotline",
                inbound=True,
                outbound=True,
                inbound_config=AddPhoneNumberManagementRequestInboundConfig(
                    allowed_addresses=["112.126.15.64/27"],
                ),
                outbound_config=AddPhoneNumberManagementRequestOutboundConfig(
                    address="xxx:xxx@sip.example.com",
                    transport="tls",
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.add(
            provider=provider,
            phone_number=phone_number,
            label=label,
            inbound_config=inbound_config,
            outbound_config=outbound_config,
            inbound=inbound,
            outbound=outbound,
            request_options=request_options,
        )
        return _response.data

    async def get(
        self, phone_number: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetPhoneNumberManagementResponse:
        """
        Retrieve detailed information for a specific phone number.

        Parameters
        ----------
        phone_number : str
            Telephone number in E.164 format. For example, +11234567890.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetPhoneNumberManagementResponse
            Request was successful. The response body contains the result of the request.

        Examples
        --------
        import asyncio

        from agoraio import AsyncAgora

        client = AsyncAgora(
            username="YOUR_USERNAME",
            password="YOUR_PASSWORD",
        )


        async def main() -> None:
            await client.phone_number_management.get(
                phone_number="phone_number",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get(phone_number, request_options=request_options)
        return _response.data

    async def delete(self, phone_number: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Remove an imported phone number from the system.

        Note: This operation only removes the number configuration from the Agora system; the number stored with the phone service provider is not deleted. After calling this endpoint, the number stops receiving calls routed through this system. To delete the number from the service provider, remove it in the service provider's console.

        Parameters
        ----------
        phone_number : str
            Telephone number in E.164 format. For example, +11234567890.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from agoraio import AsyncAgora

        client = AsyncAgora(
            username="YOUR_USERNAME",
            password="YOUR_PASSWORD",
        )


        async def main() -> None:
            await client.phone_number_management.delete(
                phone_number="phone_number",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete(phone_number, request_options=request_options)
        return _response.data

    async def update(
        self,
        phone_number: str,
        *,
        inbound_config: typing.Optional[UpdatePhoneNumberManagementRequestInboundConfig] = OMIT,
        outbound_config: typing.Optional[UpdatePhoneNumberManagementRequestOutboundConfig] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UpdatePhoneNumberManagementResponse:
        """
        Update the configuration for a phone number.

        Parameters
        ----------
        phone_number : str
            Telephone number in E.164 format. For example, +11234567890.

        inbound_config : typing.Optional[UpdatePhoneNumberManagementRequestInboundConfig]
            Update inbound call configuration. Passing `null` will clear the configuration.

        outbound_config : typing.Optional[UpdatePhoneNumberManagementRequestOutboundConfig]
            Update outbound call configuration. Passing `null` will clear the configuration.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UpdatePhoneNumberManagementResponse
            Request was successful. The response body contains the result of the request.

        Examples
        --------
        import asyncio

        from agoraio import AsyncAgora
        from agoraio.phone_number_management import (
            UpdatePhoneNumberManagementRequestInboundConfig,
            UpdatePhoneNumberManagementRequestOutboundConfig,
        )

        client = AsyncAgora(
            username="YOUR_USERNAME",
            password="YOUR_PASSWORD",
        )


        async def main() -> None:
            await client.phone_number_management.update(
                phone_number="phone_number",
                inbound_config=UpdatePhoneNumberManagementRequestInboundConfig(
                    pipeline_id="xxxxx",
                ),
                outbound_config=UpdatePhoneNumberManagementRequestOutboundConfig(
                    pipeline_id="xxxxx",
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update(
            phone_number,
            inbound_config=inbound_config,
            outbound_config=outbound_config,
            request_options=request_options,
        )
        return _response.data
