# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawPhoneNumberManagementClient, RawPhoneNumberManagementClient
from .types.import_number_request_inbound_config import ImportNumberRequestInboundConfig
from .types.import_number_request_outbound_config import ImportNumberRequestOutboundConfig
from .types.import_number_request_provider import ImportNumberRequestProvider
from .types.import_number_response import ImportNumberResponse
from .types.retrieve_number_information_response import RetrieveNumberInformationResponse
from .types.retrieve_number_list_response_item import RetrieveNumberListResponseItem
from .types.update_number_configuration_request_inbound_config import UpdateNumberConfigurationRequestInboundConfig
from .types.update_number_configuration_request_outbound_config import UpdateNumberConfigurationRequestOutboundConfig
from .types.update_number_configuration_response import UpdateNumberConfigurationResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class PhoneNumberManagementClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawPhoneNumberManagementClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawPhoneNumberManagementClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawPhoneNumberManagementClient
        """
        return self._raw_client

    def retrieve_number_list(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[RetrieveNumberListResponseItem]:
        """
        Retrieve a list of all imported phone numbers under the current account.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[RetrieveNumberListResponseItem]
            Request was successful. The response body contains a JSON array of phone number configurations.

        Examples
        --------
        from agoraio import Agora

        client = Agora(
            username="YOUR_USERNAME",
            password="YOUR_PASSWORD",
        )
        client.phone_number_management.retrieve_number_list()
        """
        _response = self._raw_client.retrieve_number_list(request_options=request_options)
        return _response.data

    def import_number(
        self,
        *,
        provider: ImportNumberRequestProvider,
        phone_number: str,
        label: str,
        inbound_config: ImportNumberRequestInboundConfig,
        outbound_config: ImportNumberRequestOutboundConfig,
        inbound: typing.Optional[bool] = OMIT,
        outbound: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ImportNumberResponse:
        """
        Import a pre-configured phone number that can be used for inbound or outbound calls.

        Parameters
        ----------
        provider : ImportNumberRequestProvider
            Number provider:
            - `byo`: BYO (Bring Your Own)
            - `twilio`: Twilio

        phone_number : str
            Telephone number in E.164 format.

        label : str
            A label used to identify the number.

        inbound_config : ImportNumberRequestInboundConfig
            SIP inbound call configuration.

        outbound_config : ImportNumberRequestOutboundConfig
            SIP outbound call configuration.

        inbound : typing.Optional[bool]
            Whether the number supports inbound calls.

        outbound : typing.Optional[bool]
            Whether the number supports outbound calls.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ImportNumberResponse
            Request was successful. The response body contains the result of the request.

        Examples
        --------
        from agoraio import Agora
        from agoraio.phone_number_management import (
            ImportNumberRequestInboundConfig,
            ImportNumberRequestOutboundConfig,
        )

        client = Agora(
            username="YOUR_USERNAME",
            password="YOUR_PASSWORD",
        )
        client.phone_number_management.import_number(
            provider="byo",
            phone_number="+19876543210",
            label="Sales Hotline",
            inbound=True,
            outbound=True,
            inbound_config=ImportNumberRequestInboundConfig(
                allowed_addresses=["112.126.15.64/27"],
            ),
            outbound_config=ImportNumberRequestOutboundConfig(
                address="xxx:xxx@sip.example.com",
                transport="tls",
            ),
        )
        """
        _response = self._raw_client.import_number(
            provider=provider,
            phone_number=phone_number,
            label=label,
            inbound_config=inbound_config,
            outbound_config=outbound_config,
            inbound=inbound,
            outbound=outbound,
            request_options=request_options,
        )
        return _response.data

    def retrieve_number_information(
        self, phone_number: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> RetrieveNumberInformationResponse:
        """
        Retrieve detailed information for a specific phone number.

        Parameters
        ----------
        phone_number : str
            Telephone number in E.164 format. For example, +11234567890.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RetrieveNumberInformationResponse
            Request was successful. The response body contains the result of the request.

        Examples
        --------
        from agoraio import Agora

        client = Agora(
            username="YOUR_USERNAME",
            password="YOUR_PASSWORD",
        )
        client.phone_number_management.retrieve_number_information(
            phone_number="phone_number",
        )
        """
        _response = self._raw_client.retrieve_number_information(phone_number, request_options=request_options)
        return _response.data

    def delete_number(self, phone_number: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Remove an imported phone number from the system.

        Note: This operation only removes the number configuration from the Agora system; the number stored with the phone service provider is not deleted. After calling this endpoint, the number stops receiving calls routed through this system. To delete the number from the service provider, remove it in the service provider's console.

        Parameters
        ----------
        phone_number : str
            Telephone number in E.164 format. For example, +11234567890.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from agoraio import Agora

        client = Agora(
            username="YOUR_USERNAME",
            password="YOUR_PASSWORD",
        )
        client.phone_number_management.delete_number(
            phone_number="phone_number",
        )
        """
        _response = self._raw_client.delete_number(phone_number, request_options=request_options)
        return _response.data

    def update_number_configuration(
        self,
        phone_number: str,
        *,
        inbound_config: typing.Optional[UpdateNumberConfigurationRequestInboundConfig] = OMIT,
        outbound_config: typing.Optional[UpdateNumberConfigurationRequestOutboundConfig] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UpdateNumberConfigurationResponse:
        """
        Update the configuration for a phone number.

        Parameters
        ----------
        phone_number : str
            Telephone number in E.164 format. For example, +11234567890.

        inbound_config : typing.Optional[UpdateNumberConfigurationRequestInboundConfig]
            Update inbound call configuration. Passing `null` will clear the configuration.

        outbound_config : typing.Optional[UpdateNumberConfigurationRequestOutboundConfig]
            Update outbound call configuration. Passing `null` will clear the configuration.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UpdateNumberConfigurationResponse
            Request was successful. The response body contains the result of the request.

        Examples
        --------
        from agoraio import Agora
        from agoraio.phone_number_management import (
            UpdateNumberConfigurationRequestInboundConfig,
            UpdateNumberConfigurationRequestOutboundConfig,
        )

        client = Agora(
            username="YOUR_USERNAME",
            password="YOUR_PASSWORD",
        )
        client.phone_number_management.update_number_configuration(
            phone_number="phone_number",
            inbound_config=UpdateNumberConfigurationRequestInboundConfig(
                pipeline_id="xxxxx",
            ),
            outbound_config=UpdateNumberConfigurationRequestOutboundConfig(
                pipeline_id="xxxxx",
            ),
        )
        """
        _response = self._raw_client.update_number_configuration(
            phone_number,
            inbound_config=inbound_config,
            outbound_config=outbound_config,
            request_options=request_options,
        )
        return _response.data


class AsyncPhoneNumberManagementClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawPhoneNumberManagementClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawPhoneNumberManagementClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawPhoneNumberManagementClient
        """
        return self._raw_client

    async def retrieve_number_list(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[RetrieveNumberListResponseItem]:
        """
        Retrieve a list of all imported phone numbers under the current account.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[RetrieveNumberListResponseItem]
            Request was successful. The response body contains a JSON array of phone number configurations.

        Examples
        --------
        import asyncio

        from agoraio import AsyncAgora

        client = AsyncAgora(
            username="YOUR_USERNAME",
            password="YOUR_PASSWORD",
        )


        async def main() -> None:
            await client.phone_number_management.retrieve_number_list()


        asyncio.run(main())
        """
        _response = await self._raw_client.retrieve_number_list(request_options=request_options)
        return _response.data

    async def import_number(
        self,
        *,
        provider: ImportNumberRequestProvider,
        phone_number: str,
        label: str,
        inbound_config: ImportNumberRequestInboundConfig,
        outbound_config: ImportNumberRequestOutboundConfig,
        inbound: typing.Optional[bool] = OMIT,
        outbound: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ImportNumberResponse:
        """
        Import a pre-configured phone number that can be used for inbound or outbound calls.

        Parameters
        ----------
        provider : ImportNumberRequestProvider
            Number provider:
            - `byo`: BYO (Bring Your Own)
            - `twilio`: Twilio

        phone_number : str
            Telephone number in E.164 format.

        label : str
            A label used to identify the number.

        inbound_config : ImportNumberRequestInboundConfig
            SIP inbound call configuration.

        outbound_config : ImportNumberRequestOutboundConfig
            SIP outbound call configuration.

        inbound : typing.Optional[bool]
            Whether the number supports inbound calls.

        outbound : typing.Optional[bool]
            Whether the number supports outbound calls.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ImportNumberResponse
            Request was successful. The response body contains the result of the request.

        Examples
        --------
        import asyncio

        from agoraio import AsyncAgora
        from agoraio.phone_number_management import (
            ImportNumberRequestInboundConfig,
            ImportNumberRequestOutboundConfig,
        )

        client = AsyncAgora(
            username="YOUR_USERNAME",
            password="YOUR_PASSWORD",
        )


        async def main() -> None:
            await client.phone_number_management.import_number(
                provider="byo",
                phone_number="+19876543210",
                label="Sales Hotline",
                inbound=True,
                outbound=True,
                inbound_config=ImportNumberRequestInboundConfig(
                    allowed_addresses=["112.126.15.64/27"],
                ),
                outbound_config=ImportNumberRequestOutboundConfig(
                    address="xxx:xxx@sip.example.com",
                    transport="tls",
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.import_number(
            provider=provider,
            phone_number=phone_number,
            label=label,
            inbound_config=inbound_config,
            outbound_config=outbound_config,
            inbound=inbound,
            outbound=outbound,
            request_options=request_options,
        )
        return _response.data

    async def retrieve_number_information(
        self, phone_number: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> RetrieveNumberInformationResponse:
        """
        Retrieve detailed information for a specific phone number.

        Parameters
        ----------
        phone_number : str
            Telephone number in E.164 format. For example, +11234567890.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RetrieveNumberInformationResponse
            Request was successful. The response body contains the result of the request.

        Examples
        --------
        import asyncio

        from agoraio import AsyncAgora

        client = AsyncAgora(
            username="YOUR_USERNAME",
            password="YOUR_PASSWORD",
        )


        async def main() -> None:
            await client.phone_number_management.retrieve_number_information(
                phone_number="phone_number",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.retrieve_number_information(phone_number, request_options=request_options)
        return _response.data

    async def delete_number(
        self, phone_number: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Remove an imported phone number from the system.

        Note: This operation only removes the number configuration from the Agora system; the number stored with the phone service provider is not deleted. After calling this endpoint, the number stops receiving calls routed through this system. To delete the number from the service provider, remove it in the service provider's console.

        Parameters
        ----------
        phone_number : str
            Telephone number in E.164 format. For example, +11234567890.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from agoraio import AsyncAgora

        client = AsyncAgora(
            username="YOUR_USERNAME",
            password="YOUR_PASSWORD",
        )


        async def main() -> None:
            await client.phone_number_management.delete_number(
                phone_number="phone_number",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_number(phone_number, request_options=request_options)
        return _response.data

    async def update_number_configuration(
        self,
        phone_number: str,
        *,
        inbound_config: typing.Optional[UpdateNumberConfigurationRequestInboundConfig] = OMIT,
        outbound_config: typing.Optional[UpdateNumberConfigurationRequestOutboundConfig] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UpdateNumberConfigurationResponse:
        """
        Update the configuration for a phone number.

        Parameters
        ----------
        phone_number : str
            Telephone number in E.164 format. For example, +11234567890.

        inbound_config : typing.Optional[UpdateNumberConfigurationRequestInboundConfig]
            Update inbound call configuration. Passing `null` will clear the configuration.

        outbound_config : typing.Optional[UpdateNumberConfigurationRequestOutboundConfig]
            Update outbound call configuration. Passing `null` will clear the configuration.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UpdateNumberConfigurationResponse
            Request was successful. The response body contains the result of the request.

        Examples
        --------
        import asyncio

        from agoraio import AsyncAgora
        from agoraio.phone_number_management import (
            UpdateNumberConfigurationRequestInboundConfig,
            UpdateNumberConfigurationRequestOutboundConfig,
        )

        client = AsyncAgora(
            username="YOUR_USERNAME",
            password="YOUR_PASSWORD",
        )


        async def main() -> None:
            await client.phone_number_management.update_number_configuration(
                phone_number="phone_number",
                inbound_config=UpdateNumberConfigurationRequestInboundConfig(
                    pipeline_id="xxxxx",
                ),
                outbound_config=UpdateNumberConfigurationRequestOutboundConfig(
                    pipeline_id="xxxxx",
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update_number_configuration(
            phone_number,
            inbound_config=inbound_config,
            outbound_config=outbound_config,
            request_options=request_options,
        )
        return _response.data
