# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import jsonable_encoder
from ..core.request_options import RequestOptions
from ..core.serialization import convert_and_respect_annotation_metadata
from ..core.unchecked_base_model import construct_type
from .types.phone_number_management_add_request_inbound_config import PhoneNumberManagementAddRequestInboundConfig
from .types.phone_number_management_add_request_outbound_config import PhoneNumberManagementAddRequestOutboundConfig
from .types.phone_number_management_add_request_provider import PhoneNumberManagementAddRequestProvider
from .types.phone_number_management_add_response import PhoneNumberManagementAddResponse
from .types.phone_number_management_get_response import PhoneNumberManagementGetResponse
from .types.phone_number_management_list_response_item import PhoneNumberManagementListResponseItem
from .types.phone_number_management_update_request_inbound_config import PhoneNumberManagementUpdateRequestInboundConfig
from .types.phone_number_management_update_request_outbound_config import (
    PhoneNumberManagementUpdateRequestOutboundConfig,
)
from .types.phone_number_management_update_response import PhoneNumberManagementUpdateResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawPhoneNumberManagementClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def list(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[typing.List[PhoneNumberManagementListResponseItem]]:
        """
        Retrieve a list of all imported phone numbers under the current account.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[typing.List[PhoneNumberManagementListResponseItem]]
            Request was successful. The response body contains a JSON array of phone number configurations.
        """
        _response = self._client_wrapper.httpx_client.request(
            "v2/phone-numbers",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.List[PhoneNumberManagementListResponseItem],
                    construct_type(
                        type_=typing.List[PhoneNumberManagementListResponseItem],  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def add(
        self,
        *,
        provider: PhoneNumberManagementAddRequestProvider,
        phone_number: str,
        label: str,
        inbound_config: PhoneNumberManagementAddRequestInboundConfig,
        outbound_config: PhoneNumberManagementAddRequestOutboundConfig,
        inbound: typing.Optional[bool] = OMIT,
        outbound: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[PhoneNumberManagementAddResponse]:
        """
        Import a pre-configured phone number that can be used for inbound or outbound calls.

        Parameters
        ----------
        provider : PhoneNumberManagementAddRequestProvider
            Number provider:
            - `byo`: BYO (Bring Your Own)
            - `twilio`: Twilio

        phone_number : str
            Telephone number in E.164 format.

        label : str
            A label used to identify the number.

        inbound_config : PhoneNumberManagementAddRequestInboundConfig
            SIP inbound call configuration.

        outbound_config : PhoneNumberManagementAddRequestOutboundConfig
            SIP outbound call configuration.

        inbound : typing.Optional[bool]
            Whether the number supports inbound calls.

        outbound : typing.Optional[bool]
            Whether the number supports outbound calls.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[PhoneNumberManagementAddResponse]
            Request was successful. The response body contains the result of the request.
        """
        _response = self._client_wrapper.httpx_client.request(
            "v2/phone-numbers",
            method="POST",
            json={
                "provider": provider,
                "phone_number": phone_number,
                "label": label,
                "inbound": inbound,
                "outbound": outbound,
                "inbound_config": convert_and_respect_annotation_metadata(
                    object_=inbound_config, annotation=PhoneNumberManagementAddRequestInboundConfig, direction="write"
                ),
                "outbound_config": convert_and_respect_annotation_metadata(
                    object_=outbound_config, annotation=PhoneNumberManagementAddRequestOutboundConfig, direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PhoneNumberManagementAddResponse,
                    construct_type(
                        type_=PhoneNumberManagementAddResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get(
        self, phone_number: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[PhoneNumberManagementGetResponse]:
        """
        Retrieve detailed information for a specific phone number.

        Parameters
        ----------
        phone_number : str
            Telephone number in E.164 format. For example, +11234567890.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[PhoneNumberManagementGetResponse]
            Request was successful. The response body contains the result of the request.
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v2/phone-numbers/{jsonable_encoder(phone_number)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PhoneNumberManagementGetResponse,
                    construct_type(
                        type_=PhoneNumberManagementGetResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def delete(
        self, phone_number: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[None]:
        """
        Remove an imported phone number from the system.

        Note: This operation only removes the number configuration from the Agora system; the number stored with the phone service provider is not deleted. After calling this endpoint, the number stops receiving calls routed through this system. To delete the number from the service provider, remove it in the service provider's console.

        Parameters
        ----------
        phone_number : str
            Telephone number in E.164 format. For example, +11234567890.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[None]
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v2/phone-numbers/{jsonable_encoder(phone_number)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return HttpResponse(response=_response, data=None)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def update(
        self,
        phone_number: str,
        *,
        inbound_config: typing.Optional[PhoneNumberManagementUpdateRequestInboundConfig] = OMIT,
        outbound_config: typing.Optional[PhoneNumberManagementUpdateRequestOutboundConfig] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[PhoneNumberManagementUpdateResponse]:
        """
        Update the configuration for a phone number.

        Parameters
        ----------
        phone_number : str
            Telephone number in E.164 format. For example, +11234567890.

        inbound_config : typing.Optional[PhoneNumberManagementUpdateRequestInboundConfig]
            Update inbound call configuration. Passing `null` will clear the configuration.

        outbound_config : typing.Optional[PhoneNumberManagementUpdateRequestOutboundConfig]
            Update outbound call configuration. Passing `null` will clear the configuration.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[PhoneNumberManagementUpdateResponse]
            Request was successful. The response body contains the result of the request.
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v2/phone-numbers/{jsonable_encoder(phone_number)}",
            method="PATCH",
            json={
                "inbound_config": convert_and_respect_annotation_metadata(
                    object_=inbound_config,
                    annotation=PhoneNumberManagementUpdateRequestInboundConfig,
                    direction="write",
                ),
                "outbound_config": convert_and_respect_annotation_metadata(
                    object_=outbound_config,
                    annotation=PhoneNumberManagementUpdateRequestOutboundConfig,
                    direction="write",
                ),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PhoneNumberManagementUpdateResponse,
                    construct_type(
                        type_=PhoneNumberManagementUpdateResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawPhoneNumberManagementClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def list(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[typing.List[PhoneNumberManagementListResponseItem]]:
        """
        Retrieve a list of all imported phone numbers under the current account.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[typing.List[PhoneNumberManagementListResponseItem]]
            Request was successful. The response body contains a JSON array of phone number configurations.
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v2/phone-numbers",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.List[PhoneNumberManagementListResponseItem],
                    construct_type(
                        type_=typing.List[PhoneNumberManagementListResponseItem],  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def add(
        self,
        *,
        provider: PhoneNumberManagementAddRequestProvider,
        phone_number: str,
        label: str,
        inbound_config: PhoneNumberManagementAddRequestInboundConfig,
        outbound_config: PhoneNumberManagementAddRequestOutboundConfig,
        inbound: typing.Optional[bool] = OMIT,
        outbound: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[PhoneNumberManagementAddResponse]:
        """
        Import a pre-configured phone number that can be used for inbound or outbound calls.

        Parameters
        ----------
        provider : PhoneNumberManagementAddRequestProvider
            Number provider:
            - `byo`: BYO (Bring Your Own)
            - `twilio`: Twilio

        phone_number : str
            Telephone number in E.164 format.

        label : str
            A label used to identify the number.

        inbound_config : PhoneNumberManagementAddRequestInboundConfig
            SIP inbound call configuration.

        outbound_config : PhoneNumberManagementAddRequestOutboundConfig
            SIP outbound call configuration.

        inbound : typing.Optional[bool]
            Whether the number supports inbound calls.

        outbound : typing.Optional[bool]
            Whether the number supports outbound calls.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[PhoneNumberManagementAddResponse]
            Request was successful. The response body contains the result of the request.
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v2/phone-numbers",
            method="POST",
            json={
                "provider": provider,
                "phone_number": phone_number,
                "label": label,
                "inbound": inbound,
                "outbound": outbound,
                "inbound_config": convert_and_respect_annotation_metadata(
                    object_=inbound_config, annotation=PhoneNumberManagementAddRequestInboundConfig, direction="write"
                ),
                "outbound_config": convert_and_respect_annotation_metadata(
                    object_=outbound_config, annotation=PhoneNumberManagementAddRequestOutboundConfig, direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PhoneNumberManagementAddResponse,
                    construct_type(
                        type_=PhoneNumberManagementAddResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get(
        self, phone_number: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[PhoneNumberManagementGetResponse]:
        """
        Retrieve detailed information for a specific phone number.

        Parameters
        ----------
        phone_number : str
            Telephone number in E.164 format. For example, +11234567890.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[PhoneNumberManagementGetResponse]
            Request was successful. The response body contains the result of the request.
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v2/phone-numbers/{jsonable_encoder(phone_number)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PhoneNumberManagementGetResponse,
                    construct_type(
                        type_=PhoneNumberManagementGetResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def delete(
        self, phone_number: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[None]:
        """
        Remove an imported phone number from the system.

        Note: This operation only removes the number configuration from the Agora system; the number stored with the phone service provider is not deleted. After calling this endpoint, the number stops receiving calls routed through this system. To delete the number from the service provider, remove it in the service provider's console.

        Parameters
        ----------
        phone_number : str
            Telephone number in E.164 format. For example, +11234567890.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[None]
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v2/phone-numbers/{jsonable_encoder(phone_number)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return AsyncHttpResponse(response=_response, data=None)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def update(
        self,
        phone_number: str,
        *,
        inbound_config: typing.Optional[PhoneNumberManagementUpdateRequestInboundConfig] = OMIT,
        outbound_config: typing.Optional[PhoneNumberManagementUpdateRequestOutboundConfig] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[PhoneNumberManagementUpdateResponse]:
        """
        Update the configuration for a phone number.

        Parameters
        ----------
        phone_number : str
            Telephone number in E.164 format. For example, +11234567890.

        inbound_config : typing.Optional[PhoneNumberManagementUpdateRequestInboundConfig]
            Update inbound call configuration. Passing `null` will clear the configuration.

        outbound_config : typing.Optional[PhoneNumberManagementUpdateRequestOutboundConfig]
            Update outbound call configuration. Passing `null` will clear the configuration.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[PhoneNumberManagementUpdateResponse]
            Request was successful. The response body contains the result of the request.
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v2/phone-numbers/{jsonable_encoder(phone_number)}",
            method="PATCH",
            json={
                "inbound_config": convert_and_respect_annotation_metadata(
                    object_=inbound_config,
                    annotation=PhoneNumberManagementUpdateRequestInboundConfig,
                    direction="write",
                ),
                "outbound_config": convert_and_respect_annotation_metadata(
                    object_=outbound_config,
                    annotation=PhoneNumberManagementUpdateRequestOutboundConfig,
                    direction="write",
                ),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    PhoneNumberManagementUpdateResponse,
                    construct_type(
                        type_=PhoneNumberManagementUpdateResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
