# This file was auto-generated by Fern from our API Definition.

import typing

AgentManagementStartRequestPropertiesParametersSilenceConfigAction = typing.Union[
    typing.Literal["speak", "think"], typing.Any
]
