# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.serialization import FieldMetadata
from ...core.unchecked_base_model import UncheckedBaseModel
from .agent_management_list_response_data_list_item import AgentManagementListResponseDataListItem


class AgentManagementListResponseData(UncheckedBaseModel):
    """
    Agent data.
    """

    count: typing.Optional[int] = pydantic.Field(default=None)
    """
    The number of agents returned.
    """

    list_: typing_extensions.Annotated[
        typing.Optional[typing.List[AgentManagementListResponseDataListItem]], FieldMetadata(alias="list")
    ] = pydantic.Field(default=None)
    """
    A list of agents that meets the criteria.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
