# This file was auto-generated by Fern from our API Definition.

import typing

AgentManagementStartRequestPropertiesTtsVendor = typing.Union[
    typing.Literal[
        "microsoft", "elevenlabs", "cartesia", "openai", "humeai", "rime", "fishaudio", "groq", "google", "amazon"
    ],
    typing.Any,
]
