# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.unchecked_base_model import UncheckedBaseModel
from .agent_management_start_request_properties_tts_vendor import AgentManagementStartRequestPropertiesTtsVendor


class AgentManagementStartRequestPropertiesTts(UncheckedBaseModel):
    """
    Text-to-speech (TTS) module configuration.
    """

    vendor: AgentManagementStartRequestPropertiesTtsVendor = pydantic.Field()
    """
    TTS provider:
    - `microsoft`: Microsoft Azure
    - `elevenlabs`: ElevenLabs
    - `cartesia`: Cartesia (Beta)
    - `openai`: OpenAI (Beta)
    - `humeai`: Hume AI (Beta)
    - `rime`: Rime (Beta)
    - `fishaudio`: Fish Audio (Beta)
    - `groq`: Groq (Beta)
    - `google`: Google (Beta)
    - `amazon`: Amazon Polly (Beta)
    """

    params: typing.Dict[str, typing.Optional[typing.Any]] = pydantic.Field()
    """
    The configuration parameters for the TTS vendor. See [TTS Overview](https://docs.agora.io/en/conversational-ai/models/tts/overview) for details.
    """

    skip_patterns: typing.Optional[typing.List[int]] = pydantic.Field(default=None)
    """
    Controls whether the TTS module skips bracketed content when reading LLM response text. Enable this feature by specifying one or more values:
    - `1`: Skip content in Chinese parentheses （）
    - `2`: Skip content in Chinese square brackets 【】
    - `3`: Skip content in parentheses ( )
    - `4`: Skip content in square brackets [ ]
    - `5`: Skip content in curly braces { }
    
    > - **Nested brackets**: When input text contains nested brackets and multiple bracket types are configured to be skipped, the system processes only the outermost brackets. The system matches from the beginning of the text and skips the first outermost bracket pair that meets the skip rule, including all nested content.
    > - **Agent memory**: The agent's short-term memory always contains the complete, unfiltered LLM text, regardless of live captioning settings.
    > - **Real-time transcript**: When enabled, transcript excludes filtered content during TTS playback but restores the complete text after each sentence finishes.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
