# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.unchecked_base_model import UncheckedBaseModel
from .list_agent_management_response_data import ListAgentManagementResponseData
from .list_agent_management_response_meta import ListAgentManagementResponseMeta


class ListAgentManagementResponse(UncheckedBaseModel):
    data: typing.Optional[ListAgentManagementResponseData] = pydantic.Field(default=None)
    """
    Agent data.
    """

    meta: typing.Optional[ListAgentManagementResponseMeta] = pydantic.Field(default=None)
    """
    Returns meta information about the list.
    """

    status: typing.Optional[str] = pydantic.Field(default=None)
    """
    Request status.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
