# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.unchecked_base_model import UncheckedBaseModel
from .start_agent_request_properties_advanced_features import StartAgentRequestPropertiesAdvancedFeatures
from .start_agent_request_properties_asr import StartAgentRequestPropertiesAsr
from .start_agent_request_properties_avatar import StartAgentRequestPropertiesAvatar
from .start_agent_request_properties_llm import StartAgentRequestPropertiesLlm
from .start_agent_request_properties_mllm import StartAgentRequestPropertiesMllm
from .start_agent_request_properties_parameters import StartAgentRequestPropertiesParameters
from .start_agent_request_properties_sal import StartAgentRequestPropertiesSal
from .start_agent_request_properties_tts import StartAgentRequestPropertiesTts
from .start_agent_request_properties_turn_detection import StartAgentRequestPropertiesTurnDetection


class StartAgentRequestProperties(UncheckedBaseModel):
    """
    Configuration details of the agent.
    """

    channel: str = pydantic.Field()
    """
    The name of the channel to join.
    """

    token: str = pydantic.Field()
    """
    The authentication token used by the agent to join the channel.
    """

    agent_rtc_uid: str = pydantic.Field()
    """
    The user ID of the agent in the channel. A value of `0` means that a random UID is generated and assigned. Set the `token` accordingly.
    """

    remote_rtc_uids: typing.List[str] = pydantic.Field()
    """
    A list of user IDs that the agent subscribes to in the channel. Only subscribed users can interact with the agent. Currently, only one user ID is supported.
    """

    enable_string_uid: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether to enable String uid:
    - `true`: Both agent and subscriber user IDs use strings.
    - `false`: Both agent and subscriber user IDs must be integers.
    """

    idle_timeout: typing.Optional[int] = pydantic.Field(default=None)
    """
    Sets the timeout after all the users specified in `remote_rtc_uids` are detected to have left the channel. When the timeout value is exceeded, the agent automatically stops and exits the channel. A value of `0` means that the agent does not exit until it is stopped manually.
    """

    advanced_features: typing.Optional[StartAgentRequestPropertiesAdvancedFeatures] = pydantic.Field(default=None)
    """
    Advanced features configuration.
    """

    asr: typing.Optional[StartAgentRequestPropertiesAsr] = pydantic.Field(default=None)
    """
    Automatic Speech Recognition (ASR) configuration.
    """

    tts: StartAgentRequestPropertiesTts = pydantic.Field()
    """
    Text-to-speech (TTS) module configuration.
    """

    llm: StartAgentRequestPropertiesLlm = pydantic.Field()
    """
    Large language model (LLM) configuration.
    """

    mllm: typing.Optional[StartAgentRequestPropertiesMllm] = pydantic.Field(default=None)
    """
    Multimodal Large Language Model (MLLM) configuration for real-time audio and text processing.
    """

    avatar: typing.Optional[StartAgentRequestPropertiesAvatar] = pydantic.Field(default=None)
    """
    Avatar configuration.
    """

    turn_detection: typing.Optional[StartAgentRequestPropertiesTurnDetection] = pydantic.Field(default=None)
    """
    Conversation turn detection settings.
    """

    sal: typing.Optional[StartAgentRequestPropertiesSal] = pydantic.Field(default=None)
    """
    Selective Attention Locking (SAL) configuration.
    """

    parameters: typing.Optional[StartAgentRequestPropertiesParameters] = pydantic.Field(default=None)
    """
    Agent configuration parameters.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
