# This file was auto-generated by Fern from our API Definition.

import typing

StartAgentManagementRequestPropertiesParametersDataChannel = typing.Union[
    typing.Literal["rtm", "datastream"], typing.Any
]
