# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import jsonable_encoder
from ..core.request_options import RequestOptions
from ..core.serialization import convert_and_respect_annotation_metadata
from ..core.unchecked_base_model import construct_type
from .types.hangup_call_response import HangupCallResponse
from .types.initiate_outbound_call_request_properties import InitiateOutboundCallRequestProperties
from .types.initiate_outbound_call_request_sip import InitiateOutboundCallRequestSip
from .types.initiate_outbound_call_response import InitiateOutboundCallResponse
from .types.retrieve_call_records_request_type import RetrieveCallRecordsRequestType
from .types.retrieve_call_records_response import RetrieveCallRecordsResponse
from .types.retrieve_call_status_response import RetrieveCallStatusResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawTelephonyClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def retrieve_call_records(
        self,
        appid: str,
        *,
        number: typing.Optional[str] = None,
        from_time: typing.Optional[int] = None,
        to_time: typing.Optional[int] = None,
        type: typing.Optional[RetrieveCallRecordsRequestType] = None,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[RetrieveCallRecordsResponse]:
        """
        Query historical call records for a specified appid based on the filter criteria.

        Parameters
        ----------
        appid : str
            The App ID of the project.

        number : typing.Optional[str]
            Filter by phone number. Can be either the calling number or the called number.

        from_time : typing.Optional[int]
            Query list start timestamp (in seconds). Default is 60 days ago.

        to_time : typing.Optional[int]
            Query list end timestamp (in seconds). Default is current time.

        type : typing.Optional[RetrieveCallRecordsRequestType]
            Call type filter:
            - `inbound`: Inbound call.
            - `outbound`: Outbound call.

            If not specified, all call types are returned.

        limit : typing.Optional[int]
            Maximum number of items returned in a single page.

        cursor : typing.Optional[str]
            Pagination cursor. Use the `agent_id` from the previous page as the cursor for the next page.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[RetrieveCallRecordsResponse]
            Request was successful. The response body contains the result of the request.
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v2/projects/{jsonable_encoder(appid)}/call",
            method="GET",
            params={
                "number": number,
                "from_time": from_time,
                "to_time": to_time,
                "type": type,
                "limit": limit,
                "cursor": cursor,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    RetrieveCallRecordsResponse,
                    construct_type(
                        type_=RetrieveCallRecordsResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def initiate_outbound_call(
        self,
        appid: str,
        *,
        name: str,
        sip: InitiateOutboundCallRequestSip,
        properties: InitiateOutboundCallRequestProperties,
        pipeline_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[InitiateOutboundCallResponse]:
        """
        Initiate an outbound call to a specified number and create an agent to join the specified RTC channel.

        Use this endpoint to initiate an outbound call to the specified number and create an agent that joins the target RTC channel. The agent waits for the callee to answer.

        Parameters
        ----------
        appid : str
            The App ID of the project.

        name : str
            The name identifier of the call session.

        sip : InitiateOutboundCallRequestSip
            SIP (Session Initiation Protocol) call configuration object.

        properties : InitiateOutboundCallRequestProperties
            Call attribute configuration. The content of this field varies depending on the invocation method:
            - **Using pipeline ID**: Simply pass in `channel`, `token`, and `agent_rtc_uid`.
            - **Using complete configuration**: Pass in the complete parameters of the [Start a conversational AI agent](https://docs.agora.io/en/conversational-ai/rest-api/agent/join) `properties`, including all required fields such as `channel`, `token`, `agent_rtc_uid`, `remote_rtc_uids`, `tts`, and `llm`.

        pipeline_id : typing.Optional[str]
            The unique ID of a published project in AI Studio.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[InitiateOutboundCallResponse]
            Request was successful. The response body contains the result of the request.
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v2/projects/{jsonable_encoder(appid)}/call",
            method="POST",
            json={
                "name": name,
                "sip": convert_and_respect_annotation_metadata(
                    object_=sip, annotation=InitiateOutboundCallRequestSip, direction="write"
                ),
                "pipeline_id": pipeline_id,
                "properties": convert_and_respect_annotation_metadata(
                    object_=properties, annotation=InitiateOutboundCallRequestProperties, direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    InitiateOutboundCallResponse,
                    construct_type(
                        type_=InitiateOutboundCallResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def retrieve_call_status(
        self, appid: str, agent_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[RetrieveCallStatusResponse]:
        """
        Retrieve the call status and related information of a specified agent.

        Parameters
        ----------
        appid : str
            The App ID of the project.

        agent_id : str
            The agent ID you obtained after successfully calling the API to initiate an outbound call.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[RetrieveCallStatusResponse]
            Request was successful. The response body contains the result of the request.
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v2/projects/{jsonable_encoder(appid)}/calls/{jsonable_encoder(agent_id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    RetrieveCallStatusResponse,
                    construct_type(
                        type_=RetrieveCallStatusResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def hangup_call(
        self, appid: str, agent_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[HangupCallResponse]:
        """
        Instruct the agent to proactively hang up the ongoing call and leave the RTC channel.

        Parameters
        ----------
        appid : str
            The App ID of the project.

        agent_id : str
            The agent ID you obtained after successfully calling the API to initiate an outbound call.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[HangupCallResponse]
            Request was successful. The response body is empty.
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v2/projects/{jsonable_encoder(appid)}/calls/{jsonable_encoder(agent_id)}/hangup",
            method="POST",
            json={},
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    HangupCallResponse,
                    construct_type(
                        type_=HangupCallResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawTelephonyClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def retrieve_call_records(
        self,
        appid: str,
        *,
        number: typing.Optional[str] = None,
        from_time: typing.Optional[int] = None,
        to_time: typing.Optional[int] = None,
        type: typing.Optional[RetrieveCallRecordsRequestType] = None,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[RetrieveCallRecordsResponse]:
        """
        Query historical call records for a specified appid based on the filter criteria.

        Parameters
        ----------
        appid : str
            The App ID of the project.

        number : typing.Optional[str]
            Filter by phone number. Can be either the calling number or the called number.

        from_time : typing.Optional[int]
            Query list start timestamp (in seconds). Default is 60 days ago.

        to_time : typing.Optional[int]
            Query list end timestamp (in seconds). Default is current time.

        type : typing.Optional[RetrieveCallRecordsRequestType]
            Call type filter:
            - `inbound`: Inbound call.
            - `outbound`: Outbound call.

            If not specified, all call types are returned.

        limit : typing.Optional[int]
            Maximum number of items returned in a single page.

        cursor : typing.Optional[str]
            Pagination cursor. Use the `agent_id` from the previous page as the cursor for the next page.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[RetrieveCallRecordsResponse]
            Request was successful. The response body contains the result of the request.
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v2/projects/{jsonable_encoder(appid)}/call",
            method="GET",
            params={
                "number": number,
                "from_time": from_time,
                "to_time": to_time,
                "type": type,
                "limit": limit,
                "cursor": cursor,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    RetrieveCallRecordsResponse,
                    construct_type(
                        type_=RetrieveCallRecordsResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def initiate_outbound_call(
        self,
        appid: str,
        *,
        name: str,
        sip: InitiateOutboundCallRequestSip,
        properties: InitiateOutboundCallRequestProperties,
        pipeline_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[InitiateOutboundCallResponse]:
        """
        Initiate an outbound call to a specified number and create an agent to join the specified RTC channel.

        Use this endpoint to initiate an outbound call to the specified number and create an agent that joins the target RTC channel. The agent waits for the callee to answer.

        Parameters
        ----------
        appid : str
            The App ID of the project.

        name : str
            The name identifier of the call session.

        sip : InitiateOutboundCallRequestSip
            SIP (Session Initiation Protocol) call configuration object.

        properties : InitiateOutboundCallRequestProperties
            Call attribute configuration. The content of this field varies depending on the invocation method:
            - **Using pipeline ID**: Simply pass in `channel`, `token`, and `agent_rtc_uid`.
            - **Using complete configuration**: Pass in the complete parameters of the [Start a conversational AI agent](https://docs.agora.io/en/conversational-ai/rest-api/agent/join) `properties`, including all required fields such as `channel`, `token`, `agent_rtc_uid`, `remote_rtc_uids`, `tts`, and `llm`.

        pipeline_id : typing.Optional[str]
            The unique ID of a published project in AI Studio.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[InitiateOutboundCallResponse]
            Request was successful. The response body contains the result of the request.
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v2/projects/{jsonable_encoder(appid)}/call",
            method="POST",
            json={
                "name": name,
                "sip": convert_and_respect_annotation_metadata(
                    object_=sip, annotation=InitiateOutboundCallRequestSip, direction="write"
                ),
                "pipeline_id": pipeline_id,
                "properties": convert_and_respect_annotation_metadata(
                    object_=properties, annotation=InitiateOutboundCallRequestProperties, direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    InitiateOutboundCallResponse,
                    construct_type(
                        type_=InitiateOutboundCallResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def retrieve_call_status(
        self, appid: str, agent_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[RetrieveCallStatusResponse]:
        """
        Retrieve the call status and related information of a specified agent.

        Parameters
        ----------
        appid : str
            The App ID of the project.

        agent_id : str
            The agent ID you obtained after successfully calling the API to initiate an outbound call.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[RetrieveCallStatusResponse]
            Request was successful. The response body contains the result of the request.
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v2/projects/{jsonable_encoder(appid)}/calls/{jsonable_encoder(agent_id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    RetrieveCallStatusResponse,
                    construct_type(
                        type_=RetrieveCallStatusResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def hangup_call(
        self, appid: str, agent_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[HangupCallResponse]:
        """
        Instruct the agent to proactively hang up the ongoing call and leave the RTC channel.

        Parameters
        ----------
        appid : str
            The App ID of the project.

        agent_id : str
            The agent ID you obtained after successfully calling the API to initiate an outbound call.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[HangupCallResponse]
            Request was successful. The response body is empty.
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v2/projects/{jsonable_encoder(appid)}/calls/{jsonable_encoder(agent_id)}/hangup",
            method="POST",
            json={},
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    HangupCallResponse,
                    construct_type(
                        type_=HangupCallResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
