# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawAgentManagementClient, RawAgentManagementClient
from .types.agent_interrupt_response import AgentInterruptResponse
from .types.agent_speak_request_priority import AgentSpeakRequestPriority
from .types.agent_speak_response import AgentSpeakResponse
from .types.get_agent_history_response import GetAgentHistoryResponse
from .types.list_agents_request_state import ListAgentsRequestState
from .types.list_agents_response import ListAgentsResponse
from .types.query_agent_status_response import QueryAgentStatusResponse
from .types.start_agent_request_properties import StartAgentRequestProperties
from .types.start_agent_response import StartAgentResponse
from .types.update_agent_request_properties import UpdateAgentRequestProperties
from .types.update_agent_response import UpdateAgentResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class AgentManagementClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawAgentManagementClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawAgentManagementClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawAgentManagementClient
        """
        return self._raw_client

    def start_agent(
        self,
        appid: str,
        *,
        name: str,
        properties: StartAgentRequestProperties,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> StartAgentResponse:
        """
        Create and start a Conversational AI agent instance.

        Parameters
        ----------
        appid : str
            The App ID of the project.

        name : str
            The unique identifier of the agent. The same identifier cannot be used repeatedly.

        properties : StartAgentRequestProperties
            Configuration details of the agent.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        StartAgentResponse
            Request was successful. The response body contains the result of the request.

        Examples
        --------
        from agoraio import Agora
        from agoraio.agent_management import (
            StartAgentRequestProperties,
            StartAgentRequestPropertiesAdvancedFeatures,
            StartAgentRequestPropertiesAsr,
            StartAgentRequestPropertiesLlm,
            StartAgentRequestPropertiesTts,
        )

        client = Agora(
            username="YOUR_USERNAME",
            password="YOUR_PASSWORD",
        )
        client.agent_management.start_agent(
            appid="appid",
            name="unique_name",
            properties=StartAgentRequestProperties(
                channel="channel_name",
                token="token",
                agent_rtc_uid="1001",
                remote_rtc_uids=["1002"],
                idle_timeout=120,
                advanced_features=StartAgentRequestPropertiesAdvancedFeatures(
                    enable_aivad=True,
                ),
                asr=StartAgentRequestPropertiesAsr(
                    language="en-US",
                ),
                tts=StartAgentRequestPropertiesTts(
                    vendor="microsoft",
                    params={
                        "key": "<your_tts_api_key>",
                        "region": "eastus",
                        "voice_name": "en-US-AndrewMultilingualNeural",
                    },
                ),
                llm=StartAgentRequestPropertiesLlm(
                    url="https://api.openai.com/v1/chat/completions",
                    api_key="<your_llm_key>",
                    system_messages=[
                        {"role": "system", "content": "You are a helpful chatbot."}
                    ],
                    params={"model": "gpt-4o-mini"},
                    max_history=32,
                    greeting_message="Hello, how can I assist you today?",
                    failure_message="Please hold on a second.",
                ),
            ),
        )
        """
        _response = self._raw_client.start_agent(
            appid, name=name, properties=properties, request_options=request_options
        )
        return _response.data

    def list_agents(
        self,
        appid: str,
        *,
        channel: typing.Optional[str] = None,
        from_time: typing.Optional[float] = None,
        to_time: typing.Optional[float] = None,
        state: typing.Optional[ListAgentsRequestState] = None,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListAgentsResponse:
        """
        Retrieve a list of agents that meet the specified conditions.

        Parameters
        ----------
        appid : str
            The App ID of the project.

        channel : typing.Optional[str]
            The channel to query for a list of agents.

        from_time : typing.Optional[float]
            The start timestamp (in seconds) for the query. Default is 2 hours ago.

        to_time : typing.Optional[float]
            The end timestamp (in seconds) for the query. Default is current time.

        state : typing.Optional[ListAgentsRequestState]
            The agent state to filter by. Only one state can be specified per query:
            - `IDLE` (0): Agent is idle.
            - `STARTING` (1): The agent is being started.
            - `RUNNING` (2): The agent is running.
            - `STOPPING` (3): The agent is stopping.
            - `STOPPED` (4): The agent has exited.
            - `RECOVERING` (5): The agent is recovering.
            - `FAILED` (6): The agent failed to execute.

        limit : typing.Optional[int]
            The maximum number of entries returned per page.

        cursor : typing.Optional[str]
            The paging cursor, indicating the starting position (`agent_id`) of the next page of results.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListAgentsResponse
            Request was successful. The response body contains the result of the request.

        Examples
        --------
        from agoraio import Agora

        client = Agora(
            username="YOUR_USERNAME",
            password="YOUR_PASSWORD",
        )
        client.agent_management.list_agents(
            appid="appid",
            channel="channel",
            from_time=1.1,
            to_time=1.1,
            state="0",
            limit=1,
            cursor="cursor",
        )
        """
        _response = self._raw_client.list_agents(
            appid,
            channel=channel,
            from_time=from_time,
            to_time=to_time,
            state=state,
            limit=limit,
            cursor=cursor,
            request_options=request_options,
        )
        return _response.data

    def query_agent_status(
        self, appid: str, agent_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> QueryAgentStatusResponse:
        """
        Get the current state information of the specified agent instance.

        Parameters
        ----------
        appid : str
            The App ID of the project.

        agent_id : str
            The agent instance ID you obtained after successfully calling `join` to start a conversational AI agent.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        QueryAgentStatusResponse
            Request was successful. The response body contains the result of the request.

        Examples
        --------
        from agoraio import Agora

        client = Agora(
            username="YOUR_USERNAME",
            password="YOUR_PASSWORD",
        )
        client.agent_management.query_agent_status(
            appid="appid",
            agent_id="agentId",
        )
        """
        _response = self._raw_client.query_agent_status(appid, agent_id, request_options=request_options)
        return _response.data

    def get_agent_history(
        self, appid: str, agent_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetAgentHistoryResponse:
        """
        Get the history of the conversation between the user and the agent.

        Call this endpoint while the agent is running to retrieve the conversation history. You can set the maximum number of cached entries using the `llm.max_history` parameter when calling the start agent endpoint. The default value is `32`.

        Parameters
        ----------
        appid : str
            The App ID of the project.

        agent_id : str
            The agent instance ID you obtained after successfully calling `join` to start a conversational AI agent.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetAgentHistoryResponse
            Request was successful. The response body contains the result of the request.

        Examples
        --------
        from agoraio import Agora

        client = Agora(
            username="YOUR_USERNAME",
            password="YOUR_PASSWORD",
        )
        client.agent_management.get_agent_history(
            appid="appid",
            agent_id="agentId",
        )
        """
        _response = self._raw_client.get_agent_history(appid, agent_id, request_options=request_options)
        return _response.data

    def stop_agent(self, appid: str, agent_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Stop the specified conversational agent instance.

        Parameters
        ----------
        appid : str
            The App ID of the project.

        agent_id : str
            The agent instance ID you obtained after successfully calling `join` to start a conversational AI agent.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from agoraio import Agora

        client = Agora(
            username="YOUR_USERNAME",
            password="YOUR_PASSWORD",
        )
        client.agent_management.stop_agent(
            appid="appid",
            agent_id="agentId",
        )
        """
        _response = self._raw_client.stop_agent(appid, agent_id, request_options=request_options)
        return _response.data

    def update_agent(
        self,
        appid: str,
        agent_id: str,
        *,
        properties: typing.Optional[UpdateAgentRequestProperties] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UpdateAgentResponse:
        """
        Adjust Conversation AI Engine parameters at runtime.

        Parameters
        ----------
        appid : str
            The App ID of the project.

        agent_id : str
            The agent instance ID you obtained after successfully calling `join` to start a conversational AI agent.

        properties : typing.Optional[UpdateAgentRequestProperties]
            Configuration properties to update.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UpdateAgentResponse
            Request was successful. The response body contains the result of the request.

        Examples
        --------
        from agoraio import Agora
        from agoraio.agent_management import (
            UpdateAgentRequestProperties,
            UpdateAgentRequestPropertiesLlm,
        )

        client = Agora(
            username="YOUR_USERNAME",
            password="YOUR_PASSWORD",
        )
        client.agent_management.update_agent(
            appid="appid",
            agent_id="agentId",
            properties=UpdateAgentRequestProperties(
                token="007eJxTYxxxxxxxxxxIaHMLAAAA0ex66",
                llm=UpdateAgentRequestPropertiesLlm(
                    system_messages=[
                        {
                            "role": "system",
                            "content": "You are a helpful assistant. xxx",
                        },
                        {
                            "role": "system",
                            "content": "Previously, user has talked about their favorite hobbies with some key topics: xxx",
                        },
                    ],
                    params={"model": "abab6.5s-chat", "max_token": 1024},
                ),
            ),
        )
        """
        _response = self._raw_client.update_agent(
            appid, agent_id, properties=properties, request_options=request_options
        )
        return _response.data

    def agent_speak(
        self,
        appid: str,
        agent_id: str,
        *,
        text: str,
        priority: typing.Optional[AgentSpeakRequestPriority] = OMIT,
        interruptable: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AgentSpeakResponse:
        """
        Broadcast a custom message using the TTS module.

        During a conversation with an agent, call this endpoint to immediately broadcast a custom message using the TTS module. Upon receiving the request, the system interrupts the agent's speech and thought process to deliver the message. This broadcast can be interrupted by human voice.

        Note: The speak API is not supported when using `mllm` configuration.

        Parameters
        ----------
        appid : str
            The App ID of the project.

        agent_id : str
            The agent instance ID you obtained after successfully calling `join` to start a conversational AI agent.

        text : str
            The broadcast message text. The maximum length of the text content is 512 bytes.

        priority : typing.Optional[AgentSpeakRequestPriority]
            Sets the priority of the message broadcast:
            - `INTERRUPT`: High priority. The agent immediately interrupts the current interaction to announce the message.
            - `APPEND`: Medium priority. The agent announces the message after the current interaction ends.
            - `IGNORE`: Low priority. If the agent is busy interacting, it ignores and discards the broadcast; the message is only announced if the agent is not interacting.

        interruptable : typing.Optional[bool]
            Whether to allow users to interrupt the agent's broadcast by speaking:
            - `true`: Allow
            - `false`: Don't allow

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AgentSpeakResponse
            Request was successful. The agent starts to broadcast the specified message.

        Examples
        --------
        from agoraio import Agora

        client = Agora(
            username="YOUR_USERNAME",
            password="YOUR_PASSWORD",
        )
        client.agent_management.agent_speak(
            appid="appid",
            agent_id="agentId",
            text="Sorry, the conversation content is not compliant.",
            priority="INTERRUPT",
            interruptable=False,
        )
        """
        _response = self._raw_client.agent_speak(
            appid, agent_id, text=text, priority=priority, interruptable=interruptable, request_options=request_options
        )
        return _response.data

    def agent_interrupt(
        self, appid: str, agent_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AgentInterruptResponse:
        """
        Interrupt the specified agent while speaking or thinking.

        Parameters
        ----------
        appid : str
            The App ID of the project.

        agent_id : str
            The agent instance ID you obtained after successfully calling `join` to start a conversational AI agent.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AgentInterruptResponse
            Request was successful. The response body contains agent information and the agent stops talking and thinking immediately.

        Examples
        --------
        from agoraio import Agora

        client = Agora(
            username="YOUR_USERNAME",
            password="YOUR_PASSWORD",
        )
        client.agent_management.agent_interrupt(
            appid="appid",
            agent_id="agentId",
        )
        """
        _response = self._raw_client.agent_interrupt(appid, agent_id, request_options=request_options)
        return _response.data


class AsyncAgentManagementClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawAgentManagementClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawAgentManagementClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawAgentManagementClient
        """
        return self._raw_client

    async def start_agent(
        self,
        appid: str,
        *,
        name: str,
        properties: StartAgentRequestProperties,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> StartAgentResponse:
        """
        Create and start a Conversational AI agent instance.

        Parameters
        ----------
        appid : str
            The App ID of the project.

        name : str
            The unique identifier of the agent. The same identifier cannot be used repeatedly.

        properties : StartAgentRequestProperties
            Configuration details of the agent.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        StartAgentResponse
            Request was successful. The response body contains the result of the request.

        Examples
        --------
        import asyncio

        from agoraio import AsyncAgora
        from agoraio.agent_management import (
            StartAgentRequestProperties,
            StartAgentRequestPropertiesAdvancedFeatures,
            StartAgentRequestPropertiesAsr,
            StartAgentRequestPropertiesLlm,
            StartAgentRequestPropertiesTts,
        )

        client = AsyncAgora(
            username="YOUR_USERNAME",
            password="YOUR_PASSWORD",
        )


        async def main() -> None:
            await client.agent_management.start_agent(
                appid="appid",
                name="unique_name",
                properties=StartAgentRequestProperties(
                    channel="channel_name",
                    token="token",
                    agent_rtc_uid="1001",
                    remote_rtc_uids=["1002"],
                    idle_timeout=120,
                    advanced_features=StartAgentRequestPropertiesAdvancedFeatures(
                        enable_aivad=True,
                    ),
                    asr=StartAgentRequestPropertiesAsr(
                        language="en-US",
                    ),
                    tts=StartAgentRequestPropertiesTts(
                        vendor="microsoft",
                        params={
                            "key": "<your_tts_api_key>",
                            "region": "eastus",
                            "voice_name": "en-US-AndrewMultilingualNeural",
                        },
                    ),
                    llm=StartAgentRequestPropertiesLlm(
                        url="https://api.openai.com/v1/chat/completions",
                        api_key="<your_llm_key>",
                        system_messages=[
                            {"role": "system", "content": "You are a helpful chatbot."}
                        ],
                        params={"model": "gpt-4o-mini"},
                        max_history=32,
                        greeting_message="Hello, how can I assist you today?",
                        failure_message="Please hold on a second.",
                    ),
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.start_agent(
            appid, name=name, properties=properties, request_options=request_options
        )
        return _response.data

    async def list_agents(
        self,
        appid: str,
        *,
        channel: typing.Optional[str] = None,
        from_time: typing.Optional[float] = None,
        to_time: typing.Optional[float] = None,
        state: typing.Optional[ListAgentsRequestState] = None,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListAgentsResponse:
        """
        Retrieve a list of agents that meet the specified conditions.

        Parameters
        ----------
        appid : str
            The App ID of the project.

        channel : typing.Optional[str]
            The channel to query for a list of agents.

        from_time : typing.Optional[float]
            The start timestamp (in seconds) for the query. Default is 2 hours ago.

        to_time : typing.Optional[float]
            The end timestamp (in seconds) for the query. Default is current time.

        state : typing.Optional[ListAgentsRequestState]
            The agent state to filter by. Only one state can be specified per query:
            - `IDLE` (0): Agent is idle.
            - `STARTING` (1): The agent is being started.
            - `RUNNING` (2): The agent is running.
            - `STOPPING` (3): The agent is stopping.
            - `STOPPED` (4): The agent has exited.
            - `RECOVERING` (5): The agent is recovering.
            - `FAILED` (6): The agent failed to execute.

        limit : typing.Optional[int]
            The maximum number of entries returned per page.

        cursor : typing.Optional[str]
            The paging cursor, indicating the starting position (`agent_id`) of the next page of results.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListAgentsResponse
            Request was successful. The response body contains the result of the request.

        Examples
        --------
        import asyncio

        from agoraio import AsyncAgora

        client = AsyncAgora(
            username="YOUR_USERNAME",
            password="YOUR_PASSWORD",
        )


        async def main() -> None:
            await client.agent_management.list_agents(
                appid="appid",
                channel="channel",
                from_time=1.1,
                to_time=1.1,
                state="0",
                limit=1,
                cursor="cursor",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_agents(
            appid,
            channel=channel,
            from_time=from_time,
            to_time=to_time,
            state=state,
            limit=limit,
            cursor=cursor,
            request_options=request_options,
        )
        return _response.data

    async def query_agent_status(
        self, appid: str, agent_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> QueryAgentStatusResponse:
        """
        Get the current state information of the specified agent instance.

        Parameters
        ----------
        appid : str
            The App ID of the project.

        agent_id : str
            The agent instance ID you obtained after successfully calling `join` to start a conversational AI agent.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        QueryAgentStatusResponse
            Request was successful. The response body contains the result of the request.

        Examples
        --------
        import asyncio

        from agoraio import AsyncAgora

        client = AsyncAgora(
            username="YOUR_USERNAME",
            password="YOUR_PASSWORD",
        )


        async def main() -> None:
            await client.agent_management.query_agent_status(
                appid="appid",
                agent_id="agentId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.query_agent_status(appid, agent_id, request_options=request_options)
        return _response.data

    async def get_agent_history(
        self, appid: str, agent_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetAgentHistoryResponse:
        """
        Get the history of the conversation between the user and the agent.

        Call this endpoint while the agent is running to retrieve the conversation history. You can set the maximum number of cached entries using the `llm.max_history` parameter when calling the start agent endpoint. The default value is `32`.

        Parameters
        ----------
        appid : str
            The App ID of the project.

        agent_id : str
            The agent instance ID you obtained after successfully calling `join` to start a conversational AI agent.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetAgentHistoryResponse
            Request was successful. The response body contains the result of the request.

        Examples
        --------
        import asyncio

        from agoraio import AsyncAgora

        client = AsyncAgora(
            username="YOUR_USERNAME",
            password="YOUR_PASSWORD",
        )


        async def main() -> None:
            await client.agent_management.get_agent_history(
                appid="appid",
                agent_id="agentId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_agent_history(appid, agent_id, request_options=request_options)
        return _response.data

    async def stop_agent(
        self, appid: str, agent_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Stop the specified conversational agent instance.

        Parameters
        ----------
        appid : str
            The App ID of the project.

        agent_id : str
            The agent instance ID you obtained after successfully calling `join` to start a conversational AI agent.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from agoraio import AsyncAgora

        client = AsyncAgora(
            username="YOUR_USERNAME",
            password="YOUR_PASSWORD",
        )


        async def main() -> None:
            await client.agent_management.stop_agent(
                appid="appid",
                agent_id="agentId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.stop_agent(appid, agent_id, request_options=request_options)
        return _response.data

    async def update_agent(
        self,
        appid: str,
        agent_id: str,
        *,
        properties: typing.Optional[UpdateAgentRequestProperties] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UpdateAgentResponse:
        """
        Adjust Conversation AI Engine parameters at runtime.

        Parameters
        ----------
        appid : str
            The App ID of the project.

        agent_id : str
            The agent instance ID you obtained after successfully calling `join` to start a conversational AI agent.

        properties : typing.Optional[UpdateAgentRequestProperties]
            Configuration properties to update.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UpdateAgentResponse
            Request was successful. The response body contains the result of the request.

        Examples
        --------
        import asyncio

        from agoraio import AsyncAgora
        from agoraio.agent_management import (
            UpdateAgentRequestProperties,
            UpdateAgentRequestPropertiesLlm,
        )

        client = AsyncAgora(
            username="YOUR_USERNAME",
            password="YOUR_PASSWORD",
        )


        async def main() -> None:
            await client.agent_management.update_agent(
                appid="appid",
                agent_id="agentId",
                properties=UpdateAgentRequestProperties(
                    token="007eJxTYxxxxxxxxxxIaHMLAAAA0ex66",
                    llm=UpdateAgentRequestPropertiesLlm(
                        system_messages=[
                            {
                                "role": "system",
                                "content": "You are a helpful assistant. xxx",
                            },
                            {
                                "role": "system",
                                "content": "Previously, user has talked about their favorite hobbies with some key topics: xxx",
                            },
                        ],
                        params={"model": "abab6.5s-chat", "max_token": 1024},
                    ),
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update_agent(
            appid, agent_id, properties=properties, request_options=request_options
        )
        return _response.data

    async def agent_speak(
        self,
        appid: str,
        agent_id: str,
        *,
        text: str,
        priority: typing.Optional[AgentSpeakRequestPriority] = OMIT,
        interruptable: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AgentSpeakResponse:
        """
        Broadcast a custom message using the TTS module.

        During a conversation with an agent, call this endpoint to immediately broadcast a custom message using the TTS module. Upon receiving the request, the system interrupts the agent's speech and thought process to deliver the message. This broadcast can be interrupted by human voice.

        Note: The speak API is not supported when using `mllm` configuration.

        Parameters
        ----------
        appid : str
            The App ID of the project.

        agent_id : str
            The agent instance ID you obtained after successfully calling `join` to start a conversational AI agent.

        text : str
            The broadcast message text. The maximum length of the text content is 512 bytes.

        priority : typing.Optional[AgentSpeakRequestPriority]
            Sets the priority of the message broadcast:
            - `INTERRUPT`: High priority. The agent immediately interrupts the current interaction to announce the message.
            - `APPEND`: Medium priority. The agent announces the message after the current interaction ends.
            - `IGNORE`: Low priority. If the agent is busy interacting, it ignores and discards the broadcast; the message is only announced if the agent is not interacting.

        interruptable : typing.Optional[bool]
            Whether to allow users to interrupt the agent's broadcast by speaking:
            - `true`: Allow
            - `false`: Don't allow

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AgentSpeakResponse
            Request was successful. The agent starts to broadcast the specified message.

        Examples
        --------
        import asyncio

        from agoraio import AsyncAgora

        client = AsyncAgora(
            username="YOUR_USERNAME",
            password="YOUR_PASSWORD",
        )


        async def main() -> None:
            await client.agent_management.agent_speak(
                appid="appid",
                agent_id="agentId",
                text="Sorry, the conversation content is not compliant.",
                priority="INTERRUPT",
                interruptable=False,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.agent_speak(
            appid, agent_id, text=text, priority=priority, interruptable=interruptable, request_options=request_options
        )
        return _response.data

    async def agent_interrupt(
        self, appid: str, agent_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AgentInterruptResponse:
        """
        Interrupt the specified agent while speaking or thinking.

        Parameters
        ----------
        appid : str
            The App ID of the project.

        agent_id : str
            The agent instance ID you obtained after successfully calling `join` to start a conversational AI agent.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AgentInterruptResponse
            Request was successful. The response body contains agent information and the agent stops talking and thinking immediately.

        Examples
        --------
        import asyncio

        from agoraio import AsyncAgora

        client = AsyncAgora(
            username="YOUR_USERNAME",
            password="YOUR_PASSWORD",
        )


        async def main() -> None:
            await client.agent_management.agent_interrupt(
                appid="appid",
                agent_id="agentId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.agent_interrupt(appid, agent_id, request_options=request_options)
        return _response.data
